#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '(1/3) 🏗️👷 Styling, testing and building your project before committing'
pnpm check-types

echo '(2/3) ✅  Linting your project'
pnpm lint-staged

echo '(3/3) ✅ Finished linting your project, checking commit message with conventional commit'
pnpm lint