/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from './apiClient';
export interface EpisodeCreate {
  episode_id: number;
  audio_url: string;
}

export type EpisodeReadId = number | null;

export type EpisodeReadTranscriptData = Record<string, unknown>;

export type EpisodeReadLanguage = string | null;

export interface EpisodeRead {
  episode_id: number;
  id?: EpisodeReadId;
  user_id: number;
  transcript_data: EpisodeReadTranscriptData;
  language?: EpisodeReadLanguage;
  progress: number;
  status: Status;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface SentenceTranslationRead {
  translated_sentence: string;
}

export type Status = (typeof Status)[keyof typeof Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export interface WordTranslationRead {
  word: string;
  translated_word: string;
  detail: string;
  word_type: string;
  phonetic: string;
}

/**
 * @summary Health
 */
export const health = (signal?: AbortSignal) => {
  return apiClient<unknown>({ url: `/ai-translator/health`, method: 'GET', signal });
};

export const getHealthQueryKey = () => {
  return [`/ai-translator/health`] as const;
};

export const getHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({
    signal,
  }) => health(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof health>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type HealthQueryError = unknown;

export function useHealth<
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof health>>,
          TError,
          Awaited<ReturnType<typeof health>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealth<
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof health>>,
          TError,
          Awaited<ReturnType<typeof health>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealth<
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health
 */

export function useHealth<
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get User Episode Ids
 */
export const getUserEpisodeIds = (signal?: AbortSignal) => {
  return apiClient<number[]>({
    url: `/ai-translator/user/episodeIds`,
    method: 'GET',
    signal,
  });
};

export const getGetUserEpisodeIdsQueryKey = () => {
  return [`/ai-translator/user/episodeIds`] as const;
};

export const getGetUserEpisodeIdsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserEpisodeIds>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getUserEpisodeIds>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserEpisodeIdsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserEpisodeIds>>
  > = ({ signal }) => getUserEpisodeIds(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserEpisodeIds>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserEpisodeIdsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserEpisodeIds>>
>;
export type GetUserEpisodeIdsQueryError = unknown;

export function useGetUserEpisodeIds<
  TData = Awaited<ReturnType<typeof getUserEpisodeIds>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserEpisodeIds>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserEpisodeIds>>,
          TError,
          Awaited<ReturnType<typeof getUserEpisodeIds>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserEpisodeIds<
  TData = Awaited<ReturnType<typeof getUserEpisodeIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserEpisodeIds>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserEpisodeIds>>,
          TError,
          Awaited<ReturnType<typeof getUserEpisodeIds>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserEpisodeIds<
  TData = Awaited<ReturnType<typeof getUserEpisodeIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserEpisodeIds>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get User Episode Ids
 */

export function useGetUserEpisodeIds<
  TData = Awaited<ReturnType<typeof getUserEpisodeIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserEpisodeIds>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserEpisodeIdsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create Transcript
 */
export const createTranscript = (
  episodeCreate: EpisodeCreate,
  signal?: AbortSignal,
) => {
  return apiClient<unknown>({
    url: `/ai-translator/transcripts`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: episodeCreate,
    signal,
  });
};

export const getCreateTranscriptMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTranscript>>,
    TError,
    { data: EpisodeCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTranscript>>,
  TError,
  { data: EpisodeCreate },
  TContext
> => {
  const mutationKey = ['createTranscript'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTranscript>>,
    { data: EpisodeCreate }
  > = props => {
    const { data } = props ?? {};

    return createTranscript(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTranscriptMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTranscript>>
>;
export type CreateTranscriptMutationBody = EpisodeCreate;
export type CreateTranscriptMutationError = HTTPValidationError;

/**
 * @summary Create Transcript
 */
export const useCreateTranscript = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTranscript>>,
      TError,
      { data: EpisodeCreate },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTranscript>>,
  TError,
  { data: EpisodeCreate },
  TContext
> => {
  const mutationOptions = getCreateTranscriptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Transcription
 */
export const getTranscriptByEpisodeId = (
  episodeId: number,
  signal?: AbortSignal,
) => {
  return apiClient<EpisodeRead>({
    url: `/ai-translator/transcript/${episodeId}`,
    method: 'GET',
    signal,
  });
};

export const getGetTranscriptByEpisodeIdQueryKey = (episodeId?: number) => {
  return [`/ai-translator/transcript/${episodeId}`] as const;
};

export const getGetTranscriptByEpisodeIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
  TError = HTTPValidationError,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTranscriptByEpisodeIdQueryKey(episodeId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTranscriptByEpisodeId>>
  > = ({ signal }) => getTranscriptByEpisodeId(episodeId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!episodeId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTranscriptByEpisodeIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTranscriptByEpisodeId>>
>;
export type GetTranscriptByEpisodeIdQueryError = HTTPValidationError;

export function useGetTranscriptByEpisodeId<
  TData = Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
  TError = HTTPValidationError,
>(
  episodeId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
          TError,
          Awaited<ReturnType<typeof getTranscriptByEpisodeId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTranscriptByEpisodeId<
  TData = Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
  TError = HTTPValidationError,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
          TError,
          Awaited<ReturnType<typeof getTranscriptByEpisodeId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTranscriptByEpisodeId<
  TData = Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
  TError = HTTPValidationError,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Transcription
 */

export function useGetTranscriptByEpisodeId<
  TData = Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
  TError = HTTPValidationError,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptByEpisodeId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTranscriptByEpisodeIdQueryOptions(
    episodeId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Translate Word
 */
export const translateWord = (
  word: string,
  sentence: string,
  signal?: AbortSignal,
) => {
  return apiClient<WordTranslationRead>({
    url: `/ai-translator/translate/word/${word}/${sentence}`,
    method: 'GET',
    signal,
  });
};

export const getTranslateWordQueryKey = (word?: string, sentence?: string) => {
  return [`/ai-translator/translate/word/${word}/${sentence}`] as const;
};

export const getTranslateWordQueryOptions = <
  TData = Awaited<ReturnType<typeof translateWord>>,
  TError = HTTPValidationError,
>(
  word: string,
  sentence: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof translateWord>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTranslateWordQueryKey(word, sentence);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof translateWord>>> = ({
    signal,
  }) => translateWord(word, sentence, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(word && sentence),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof translateWord>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TranslateWordQueryResult = NonNullable<
  Awaited<ReturnType<typeof translateWord>>
>;
export type TranslateWordQueryError = HTTPValidationError;

export function useTranslateWord<
  TData = Awaited<ReturnType<typeof translateWord>>,
  TError = HTTPValidationError,
>(
  word: string,
  sentence: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof translateWord>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof translateWord>>,
          TError,
          Awaited<ReturnType<typeof translateWord>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTranslateWord<
  TData = Awaited<ReturnType<typeof translateWord>>,
  TError = HTTPValidationError,
>(
  word: string,
  sentence: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof translateWord>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof translateWord>>,
          TError,
          Awaited<ReturnType<typeof translateWord>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTranslateWord<
  TData = Awaited<ReturnType<typeof translateWord>>,
  TError = HTTPValidationError,
>(
  word: string,
  sentence: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof translateWord>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Translate Word
 */

export function useTranslateWord<
  TData = Awaited<ReturnType<typeof translateWord>>,
  TError = HTTPValidationError,
>(
  word: string,
  sentence: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof translateWord>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTranslateWordQueryOptions(word, sentence, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Translate Sentence
 */
export const translateSentence = (
  sentence: string,
  sentenceId: number,
  episodeId: number,
  signal?: AbortSignal,
) => {
  return apiClient<SentenceTranslationRead>({
    url: `/ai-translator/translate/sentence/${sentence}/sentenceId/${sentenceId}/episodeId/${episodeId}`,
    method: 'GET',
    signal,
  });
};

export const getTranslateSentenceQueryKey = (
  sentence?: string,
  sentenceId?: number,
  episodeId?: number,
) => {
  return [`/ai-translator/translate/sentence/${sentence}/sentenceId/${sentenceId}/episodeId/${episodeId}`,
  ] as const;
};

export const getTranslateSentenceQueryOptions = <
  TData = Awaited<ReturnType<typeof translateSentence>>,
  TError = HTTPValidationError,
>(
  sentence: string,
  sentenceId: number,
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translateSentence>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getTranslateSentenceQueryKey(sentence, sentenceId, episodeId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof translateSentence>>
  > = ({ signal }) =>
    translateSentence(sentence, sentenceId, episodeId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(sentence && sentenceId && episodeId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof translateSentence>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TranslateSentenceQueryResult = NonNullable<
  Awaited<ReturnType<typeof translateSentence>>
>;
export type TranslateSentenceQueryError = HTTPValidationError;

export function useTranslateSentence<
  TData = Awaited<ReturnType<typeof translateSentence>>,
  TError = HTTPValidationError,
>(
  sentence: string,
  sentenceId: number,
  episodeId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translateSentence>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof translateSentence>>,
          TError,
          Awaited<ReturnType<typeof translateSentence>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTranslateSentence<
  TData = Awaited<ReturnType<typeof translateSentence>>,
  TError = HTTPValidationError,
>(
  sentence: string,
  sentenceId: number,
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translateSentence>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof translateSentence>>,
          TError,
          Awaited<ReturnType<typeof translateSentence>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTranslateSentence<
  TData = Awaited<ReturnType<typeof translateSentence>>,
  TError = HTTPValidationError,
>(
  sentence: string,
  sentenceId: number,
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translateSentence>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Translate Sentence
 */

export function useTranslateSentence<
  TData = Awaited<ReturnType<typeof translateSentence>>,
  TError = HTTPValidationError,
>(
  sentence: string,
  sentenceId: number,
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translateSentence>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTranslateSentenceQueryOptions(
    sentence,
    sentenceId,
    episodeId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Stream Transcript Progress
 */
export const streamTranscriptProgress = (
  transcriptId: number,
  signal?: AbortSignal,
) => {
  return apiClient<unknown>({
    url: `/ai-translator/transcript/stream/${transcriptId}`,
    method: 'GET',
    signal,
  });
};

export const getStreamTranscriptProgressQueryKey = (transcriptId?: number) => {
  return [`/ai-translator/transcript/stream/${transcriptId}`] as const;
};

export const getStreamTranscriptProgressQueryOptions = <
  TData = Awaited<ReturnType<typeof streamTranscriptProgress>>,
  TError = HTTPValidationError,
>(
  transcriptId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamTranscriptProgress>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStreamTranscriptProgressQueryKey(transcriptId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof streamTranscriptProgress>>
  > = ({ signal }) => streamTranscriptProgress(transcriptId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!transcriptId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof streamTranscriptProgress>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StreamTranscriptProgressQueryResult = NonNullable<
  Awaited<ReturnType<typeof streamTranscriptProgress>>
>;
export type StreamTranscriptProgressQueryError = HTTPValidationError;

export function useStreamTranscriptProgress<
  TData = Awaited<ReturnType<typeof streamTranscriptProgress>>,
  TError = HTTPValidationError,
>(
  transcriptId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamTranscriptProgress>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamTranscriptProgress>>,
          TError,
          Awaited<ReturnType<typeof streamTranscriptProgress>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStreamTranscriptProgress<
  TData = Awaited<ReturnType<typeof streamTranscriptProgress>>,
  TError = HTTPValidationError,
>(
  transcriptId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamTranscriptProgress>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamTranscriptProgress>>,
          TError,
          Awaited<ReturnType<typeof streamTranscriptProgress>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStreamTranscriptProgress<
  TData = Awaited<ReturnType<typeof streamTranscriptProgress>>,
  TError = HTTPValidationError,
>(
  transcriptId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamTranscriptProgress>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Stream Transcript Progress
 */

export function useStreamTranscriptProgress<
  TData = Awaited<ReturnType<typeof streamTranscriptProgress>>,
  TError = HTTPValidationError,
>(
  transcriptId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamTranscriptProgress>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStreamTranscriptProgressQueryOptions(
    transcriptId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
