/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from './apiClient';
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface Token {
  access_token: string;
  token_type?: string;
}

export type UserCreateFullName = string | null;

export interface UserCreate {
  email: string;
  full_name?: UserCreateFullName;
  is_active?: boolean;
  password: string;
}

export type UserReadFullName = string | null;

export interface UserRead {
  email: string;
  full_name?: UserReadFullName;
  is_active?: boolean;
  id: number;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export interface VerifyTokenVerifyGetParams {
  token: string;
}

/**
 * @summary Health
 */
export const healthHealthGet = (signal?: AbortSignal) => {
  return apiClient<unknown>({ url: `/auth/health`, method: 'GET', signal });
};

export const getHealthHealthGetQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthHealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthHealthGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({
    signal,
  }) => healthHealthGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthHealthGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthHealthGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthHealthGet>>
>;
export type HealthHealthGetQueryError = unknown;

export function useHealthHealthGet<
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthHealthGet<
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthHealthGet<
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health
 */

export function useHealthHealthGet<
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthHealthGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Register User
 */
export const registerUserRegisterPost = (
  userCreate: UserCreate,
  signal?: AbortSignal,
) => {
  return apiClient<UserRead>({
    url: `/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userCreate,
    signal,
  });
};

export const getRegisterUserRegisterPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUserRegisterPost>>,
    TError,
    { data: UserCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUserRegisterPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  const mutationKey = ['registerUserRegisterPost'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUserRegisterPost>>,
    { data: UserCreate }
  > = props => {
    const { data } = props ?? {};

    return registerUserRegisterPost(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterUserRegisterPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerUserRegisterPost>>
>;
export type RegisterUserRegisterPostMutationBody = UserCreate;
export type RegisterUserRegisterPostMutationError = HTTPValidationError;

/**
 * @summary Register User
 */
export const useRegisterUserRegisterPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerUserRegisterPost>>,
      TError,
      { data: UserCreate },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registerUserRegisterPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  const mutationOptions = getRegisterUserRegisterPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Login User
 */
export const loginUserLoginPost = (
  userCreate: UserCreate,
  signal?: AbortSignal,
) => {
  return apiClient<Token>({
    url: `/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userCreate,
    signal,
  });
};

export const getLoginUserLoginPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUserLoginPost>>,
    TError,
    { data: UserCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUserLoginPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  const mutationKey = ['loginUserLoginPost'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUserLoginPost>>,
    { data: UserCreate }
  > = props => {
    const { data } = props ?? {};

    return loginUserLoginPost(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUserLoginPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUserLoginPost>>
>;
export type LoginUserLoginPostMutationBody = UserCreate;
export type LoginUserLoginPostMutationError = HTTPValidationError;

/**
 * @summary Login User
 */
export const useLoginUserLoginPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginUserLoginPost>>,
      TError,
      { data: UserCreate },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loginUserLoginPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  const mutationOptions = getLoginUserLoginPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Verify Token
 */
export const verifyTokenVerifyGet = (
  params: VerifyTokenVerifyGetParams,
  signal?: AbortSignal,
) => {
  return apiClient<unknown>({ url: `/auth/verify`, method: 'GET', params, signal });
};

export const getVerifyTokenVerifyGetQueryKey = (
  params?: VerifyTokenVerifyGetParams,
) => {
  return [`/verify`, ...(params ? [params] : [])] as const;
};

export const getVerifyTokenVerifyGetQueryOptions = <
  TData = Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
  TError = HTTPValidationError,
>(
  params: VerifyTokenVerifyGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getVerifyTokenVerifyGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof verifyTokenVerifyGet>>
  > = ({ signal }) => verifyTokenVerifyGet(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VerifyTokenVerifyGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof verifyTokenVerifyGet>>
>;
export type VerifyTokenVerifyGetQueryError = HTTPValidationError;

export function useVerifyTokenVerifyGet<
  TData = Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
  TError = HTTPValidationError,
>(
  params: VerifyTokenVerifyGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
          TError,
          Awaited<ReturnType<typeof verifyTokenVerifyGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyTokenVerifyGet<
  TData = Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
  TError = HTTPValidationError,
>(
  params: VerifyTokenVerifyGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
          TError,
          Awaited<ReturnType<typeof verifyTokenVerifyGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyTokenVerifyGet<
  TData = Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
  TError = HTTPValidationError,
>(
  params: VerifyTokenVerifyGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Verify Token
 */

export function useVerifyTokenVerifyGet<
  TData = Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
  TError = HTTPValidationError,
>(
  params: VerifyTokenVerifyGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyTokenVerifyGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getVerifyTokenVerifyGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
