/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from './apiClient';
export type FeedReadImage = string | null;

export interface FeedRead {
  url: string;
  image?: FeedReadImage;
  title: string;
  author: string;
  id: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type Lang = (typeof Lang)[keyof typeof Lang];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Lang = {
  en: 'en',
  vi: 'vi',
  jp: 'jp',
} as const;

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetRecentFeedsFeedsGetParams = {
  /**
   * Language code, e.g., 'en' or 'vi'
   */
  lang?: Lang;
  limit?: number;
  offset?: number;
};

export type GetFeedEpisodesFeedsFeedIdEpisodesGetParams = {
  max_items?: number;
};

/**
 * @summary Health
 */
export const healthHealthGet = (signal?: AbortSignal) => {
  return apiClient<unknown>({ url: `/podcast/health`, method: 'GET', signal });
};

export const getHealthHealthGetQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthHealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthHealthGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({
    signal,
  }) => healthHealthGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthHealthGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthHealthGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthHealthGet>>
>;
export type HealthHealthGetQueryError = unknown;

export function useHealthHealthGet<
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthHealthGet<
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthHealthGet<
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health
 */

export function useHealthHealthGet<
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthHealthGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Recent Feeds
 */
export const getRecentFeedsFeedsGet = (
  params?: GetRecentFeedsFeedsGetParams,
  signal?: AbortSignal,
) => {
  return apiClient<FeedRead[]>({
    url: `/podcast/feeds`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetRecentFeedsFeedsGetQueryKey = (
  params?: GetRecentFeedsFeedsGetParams,
) => {
  return [`/feeds`, ...(params ? [params] : [])] as const;
};

export const getGetRecentFeedsFeedsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetRecentFeedsFeedsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRecentFeedsFeedsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>
  > = ({ signal }) => getRecentFeedsFeedsGet(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecentFeedsFeedsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>
>;
export type GetRecentFeedsFeedsGetQueryError = HTTPValidationError;

export function useGetRecentFeedsFeedsGet<
  TData = Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
  TError = HTTPValidationError,
>(
  params: undefined | GetRecentFeedsFeedsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
          TError,
          Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentFeedsFeedsGet<
  TData = Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetRecentFeedsFeedsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
          TError,
          Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentFeedsFeedsGet<
  TData = Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetRecentFeedsFeedsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Recent Feeds
 */

export function useGetRecentFeedsFeedsGet<
  TData = Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetRecentFeedsFeedsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentFeedsFeedsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecentFeedsFeedsGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Feed Episodes
 */
export const getFeedEpisodesFeedsFeedIdEpisodesGet = (
  feedId: number,
  params?: GetFeedEpisodesFeedsFeedIdEpisodesGetParams,
  signal?: AbortSignal,
) => {
  return apiClient<unknown>({
    url: `/feeds/${feedId}/episodes`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetFeedEpisodesFeedsFeedIdEpisodesGetQueryKey = (
  feedId?: number,
  params?: GetFeedEpisodesFeedsFeedIdEpisodesGetParams,
) => {
  return [`/feeds/${feedId}/episodes`, ...(params ? [params] : [])] as const;
};

export const getGetFeedEpisodesFeedsFeedIdEpisodesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params?: GetFeedEpisodesFeedsFeedIdEpisodesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFeedEpisodesFeedsFeedIdEpisodesGetQueryKey(feedId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>
  > = ({ signal }) =>
    getFeedEpisodesFeedsFeedIdEpisodesGet(feedId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!feedId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFeedEpisodesFeedsFeedIdEpisodesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>
>;
export type GetFeedEpisodesFeedsFeedIdEpisodesGetQueryError =
  HTTPValidationError;

export function useGetFeedEpisodesFeedsFeedIdEpisodesGet<
  TData = Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params: undefined | GetFeedEpisodesFeedsFeedIdEpisodesGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
          TError,
          Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFeedEpisodesFeedsFeedIdEpisodesGet<
  TData = Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params?: GetFeedEpisodesFeedsFeedIdEpisodesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
          TError,
          Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFeedEpisodesFeedsFeedIdEpisodesGet<
  TData = Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params?: GetFeedEpisodesFeedsFeedIdEpisodesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Feed Episodes
 */

export function useGetFeedEpisodesFeedsFeedIdEpisodesGet<
  TData = Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params?: GetFeedEpisodesFeedsFeedIdEpisodesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodesFeedsFeedIdEpisodesGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFeedEpisodesFeedsFeedIdEpisodesGetQueryOptions(
    feedId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
