/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from './apiClient';
export type EpisodeReadImageUrl = string | null;

export type EpisodeReadEpisode = number | null;

export type EpisodeReadEpisodeType = string | null;

export interface EpisodeRead {
  enclosure_url: string;
  enclosure_type: string;
  duration: number;
  feed_language: string;
  image_url?: EpisodeReadImageUrl;
  episode?: EpisodeReadEpisode;
  episode_type?: EpisodeReadEpisodeType;
  episode_title: string;
  episode_description: string;
  episode_pub_date: number;
  id: string;
}

export type EpisodeRecentReadImageUrl = string | null;

export type EpisodeRecentReadEpisode = number | null;

export type EpisodeRecentReadEpisodeType = string | null;

export interface EpisodeRecentRead {
  enclosure_url: string;
  enclosure_type: string;
  duration: number;
  feed_language: string;
  image_url?: EpisodeRecentReadImageUrl;
  episode?: EpisodeRecentReadEpisode;
  episode_type?: EpisodeRecentReadEpisodeType;
  episode_title: string;
  episode_description: string;
  episode_pub_date: number;
  id: string;
  updated_at: string;
  created_at: string;
}

export type FeedReadImage = string | null;

export interface FeedRead {
  url: string;
  image?: FeedReadImage;
  title: string;
  author: string;
  id: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type Lang = (typeof Lang)[keyof typeof Lang];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Lang = {
  en: 'en',
  vi: 'vi',
  jp: 'jp',
} as const;

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export interface GetRecentFeedsParams {
  /**
   * Language code, e.g., 'en' or 'vi'
   */
  lang?: Lang;
  limit?: number;
  offset?: number;
}

export interface GetFeedEpisodesParams {
  max_items?: number;
}

/**
 * @summary Health
 */
export const health = (signal?: AbortSignal) => {
  return apiClient<unknown>({ url: `/podcast/health`, method: 'GET', signal });
};

export const getHealthQueryKey = () => {
  return [`/podcast/health`] as const;
};

export const getHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({
    signal,
  }) => health(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof health>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type HealthQueryError = unknown;

export function useHealth<
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof health>>,
          TError,
          Awaited<ReturnType<typeof health>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealth<
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof health>>,
          TError,
          Awaited<ReturnType<typeof health>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealth<
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health
 */

export function useHealth<
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Recent Feeds
 */
export const getRecentFeeds = (
  params?: GetRecentFeedsParams,
  signal?: AbortSignal,
) => {
  return apiClient<FeedRead[]>({
    url: `/podcast/feeds`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetRecentFeedsQueryKey = (params?: GetRecentFeedsParams) => {
  return [`/podcast/feeds`, ...(params ? [params] : [])] as const;
};

export const getGetRecentFeedsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecentFeeds>>,
  TError = HTTPValidationError,
>(
  params?: GetRecentFeedsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeeds>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRecentFeedsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentFeeds>>> = ({
    signal,
  }) => getRecentFeeds(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecentFeeds>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecentFeedsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentFeeds>>
>;
export type GetRecentFeedsQueryError = HTTPValidationError;

export function useGetRecentFeeds<
  TData = Awaited<ReturnType<typeof getRecentFeeds>>,
  TError = HTTPValidationError,
>(
  params: undefined | GetRecentFeedsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeeds>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentFeeds>>,
          TError,
          Awaited<ReturnType<typeof getRecentFeeds>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentFeeds<
  TData = Awaited<ReturnType<typeof getRecentFeeds>>,
  TError = HTTPValidationError,
>(
  params?: GetRecentFeedsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeeds>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentFeeds>>,
          TError,
          Awaited<ReturnType<typeof getRecentFeeds>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentFeeds<
  TData = Awaited<ReturnType<typeof getRecentFeeds>>,
  TError = HTTPValidationError,
>(
  params?: GetRecentFeedsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeeds>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Recent Feeds
 */

export function useGetRecentFeeds<
  TData = Awaited<ReturnType<typeof getRecentFeeds>>,
  TError = HTTPValidationError,
>(
  params?: GetRecentFeedsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeeds>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecentFeedsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Feed Episodes
 */
export const getFeedEpisodes = (
  feedId: number,
  params?: GetFeedEpisodesParams,
  signal?: AbortSignal,
) => {
  return apiClient<EpisodeRead[]>({
    url: `/podcast/feeds/${feedId}/episodes`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetFeedEpisodesQueryKey = (
  feedId?: number,
  params?: GetFeedEpisodesParams,
) => {
  return [`/podcast/feeds/${feedId}/episodes`, ...(params ? [params] : [])] as const;
};

export const getGetFeedEpisodesQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeedEpisodes>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params?: GetFeedEpisodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodes>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFeedEpisodesQueryKey(feedId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeedEpisodes>>> = ({
    signal,
  }) => getFeedEpisodes(feedId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!feedId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeedEpisodes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFeedEpisodesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeedEpisodes>>
>;
export type GetFeedEpisodesQueryError = HTTPValidationError;

export function useGetFeedEpisodes<
  TData = Awaited<ReturnType<typeof getFeedEpisodes>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params: undefined | GetFeedEpisodesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedEpisodes>>,
          TError,
          Awaited<ReturnType<typeof getFeedEpisodes>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFeedEpisodes<
  TData = Awaited<ReturnType<typeof getFeedEpisodes>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params?: GetFeedEpisodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedEpisodes>>,
          TError,
          Awaited<ReturnType<typeof getFeedEpisodes>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFeedEpisodes<
  TData = Awaited<ReturnType<typeof getFeedEpisodes>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params?: GetFeedEpisodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Feed Episodes
 */

export function useGetFeedEpisodes<
  TData = Awaited<ReturnType<typeof getFeedEpisodes>>,
  TError = HTTPValidationError,
>(
  feedId: number,
  params?: GetFeedEpisodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedEpisodes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFeedEpisodesQueryOptions(feedId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get User Episodes
 */
export const getUserEpisodes = (signal?: AbortSignal) => {
  return apiClient<EpisodeRecentRead[]>({
    url: `/podcast/user/episodes`,
    method: 'GET',
    signal,
  });
};

export const getGetUserEpisodesQueryKey = () => {
  return [`/podcast/user/episodes`] as const;
};

export const getGetUserEpisodesQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserEpisodes>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUserEpisodes>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserEpisodesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserEpisodes>>> = ({
    signal,
  }) => getUserEpisodes(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserEpisodes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserEpisodesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserEpisodes>>
>;
export type GetUserEpisodesQueryError = unknown;

export function useGetUserEpisodes<
  TData = Awaited<ReturnType<typeof getUserEpisodes>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserEpisodes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserEpisodes>>,
          TError,
          Awaited<ReturnType<typeof getUserEpisodes>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserEpisodes<
  TData = Awaited<ReturnType<typeof getUserEpisodes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserEpisodes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserEpisodes>>,
          TError,
          Awaited<ReturnType<typeof getUserEpisodes>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserEpisodes<
  TData = Awaited<ReturnType<typeof getUserEpisodes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserEpisodes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get User Episodes
 */

export function useGetUserEpisodes<
  TData = Awaited<ReturnType<typeof getUserEpisodes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserEpisodes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserEpisodesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
